name: cra-deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        CI=false npm ci
        CI=false npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.3.2
      with:
        BRANCH: gh-pages
        FOLDER: build